apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: helloworld-ds
  labels:
    app: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: gaje85/springbootdockerdemo
        ports:
        - name: node-port
          containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
        
